Repository SherryLabs/sherry-sdk, pull requests merged in 2025-06, with the labels that each got.

#87 docs: add youtube tutorial `iframe` for guide pages
  README.md
  docs/docs/guides/guide-en.mdx
  docs/docs/guides/guide-es.mdx
Labels: documentation

#92 [Merge] Develop into Main | Re-updating docs
  docs/docs/guides/guide-en.mdx
  docs/docs/guides/guide-es.mdx
  docs/package-lock.json
  docs/package.json
  docs/yarn.lock
Labels: bug, documentation

#93 [Merge] Develop | Executors Added and Test , Working with Proxy
  package.json
  src/executors/baseExecutor.ts
  src/executors/dynamicExecutor.ts
  src/executors/index.ts
  src/executors/miniAppExecutor.ts
  src/headers/headers.ts
  src/index.ts
  tests/executors/dynamic-executor.test.ts
Labels: documentation, enhancement, feature

#95 Improving Docs - Integration Removed
  docs/docs/guides/guide-en.mdx
  docs/docs/guides/guide-es.mdx
  docs/docs/integrate-us/trigger-ui-extension.mdx
  docs/docs/integrate-us/trigger-ui.mdx
  docs/sidebars.ts
  package.json
Labels: documentation, enhancement

#96 improving docs
  docs/docs/getting-started/keyconcepts.md
  docs/docs/sdk/creating-miniapps.md
Labels: documentation, enhancement
