Repository SherryLabs/sherry-sdk, pull requests merged in 2025-05, with the labels that each got.

#74 [Merge] Develop into MAIN
  README.md
  docs/docs/sdk/action-types/transfer-actions.md
  jest.config.js
  jest.setup.js
  package.json
  src/examples/dynamic-miniapp.ts
  src/examples/example-miniapps.ts
  src/examples/mixed-miniapp.ts
  src/examples/transfer-miniapps.ts
  src/executors/dynamicExecutor.ts
  src/interface/actions/blockchainAction.ts
  src/interface/actions/dynamicAction.ts
  src/interface/actions/transferAction.ts
  src/interface/index.ts
  src/interface/inputs.ts
  src/interface/response/executionResponse.ts
  src/sherry-internal-use/analyzer/metadataAnalyzer.ts
  src/sherry-internal-use/engine/actionExecutor.ts
  src/templates/templates.ts
  src/validators/blockchainActionValidator.ts
  src/validators/httpActionValidator.ts
  src/validators/paramTypeUtils.ts
  src/validators/parameterValidator.ts
  src/validators/transferActionValidator.ts
  tests/examples/dynamic-miniapp.test.ts
  tests/executors/dynamic-executor.test.ts
  tests/interface/templates.test.ts
  tests/validators/transferActionValidator.test.ts
  yarn.lock
Labels: enhancement

#75 Feature/newdocs
  .github/workflows/format.yml
  .github/workflows/test.yml
  docs/docs/chainlogic/chains.md
  docs/docs/chainlogic/crosschain.md
  docs/docs/chainlogic/supported.md
  docs/docs/intro.mdx
  docs/docs/keyconcepts/actions.md
  docs/docs/keyconcepts/creatingminiapp.md
  docs/docs/keyconcepts/examples.md
  docs/docs/keyconcepts/keyconcepts.md
  docs/docs/keyconcepts/metadata.md
  docs/docs/keyconcepts/nextsteps.md
  docs/docs/keyconcepts/stepbystep.md
  docs/docs/quickstart/quickstart.md
  docs/docusaurus.config.ts
  docs/package-lock.json
  docs/package.json
  docs/sidebars.ts
  docs/yarn.lock
Labels: documentation, enhancement

#77 Feature/support post serialize tx
  docs/docs/chainlogic/chains.md
  docs/docs/chainlogic/crosschain.md
  docs/docs/chainlogic/supported.md
  docs/docs/guides/guide-en.md
  docs/docs/guides/guide-es.md
  docs/docs/intro.mdx
  docs/docs/keyconcepts/actions.md
  docs/docs/keyconcepts/creatingminiapp.md
  docs/docs/keyconcepts/examples.md
  docs/docs/keyconcepts/keyconcepts.md
  docs/docs/keyconcepts/metadata.md
  docs/docs/keyconcepts/nextsteps.md
  docs/docs/keyconcepts/stepbystep.md
  docs/docs/quickstart/quickstart.md
  docs/docusaurus.config.ts
  docs/sidebars.ts
  package.json
Labels: documentation, enhancement

#78 [Merge] Develop into Main
  docs/docs/chainlogic/chains.md
  docs/docs/chainlogic/crosschain.md
  docs/docs/chainlogic/supported.md
  docs/docs/guides/guide-en.md
  docs/docs/guides/guide-es.md
  docs/docs/intro.mdx
  docs/docs/keyconcepts/actions.md
  docs/docs/keyconcepts/creatingminiapp.md
  docs/docs/keyconcepts/examples.md
  docs/docs/keyconcepts/keyconcepts.md
  docs/docs/keyconcepts/metadata.md
  docs/docs/keyconcepts/nextsteps.md
  docs/docs/keyconcepts/stepbystep.md
  docs/docs/quickstart/quickstart.md
  docs/docusaurus.config.ts
  docs/sidebars.ts
  package.json
Labels: enhancement

#80 Documentación
  docs/docs/chainlogic/crosschain.md
  docs/docs/keyconcepts/actions.md
  docs/docs/keyconcepts/creatingminiapp.md
  docs/docs/keyconcepts/creatingminiapp.mdx
Labels: documentation

#81 [Merge] Develop into Main / Publish Docs
  docs/docs/chainlogic/crosschain.md
  docs/docs/keyconcepts/actions.md
  docs/docs/keyconcepts/creatingminiapp.md
  docs/docs/keyconcepts/creatingminiapp.mdx
Labels: enhancement

#82 Feature/support post serialize tx
  README.md
  docs/docs/api-reference/action-types/blockchain-actions.md
  docs/docs/api-reference/action-types/http-actions.md
  docs/docs/api-reference/action-types/nested-action-flows.md
  docs/docs/api-reference/action-types/transfer-actions.md
  docs/docs/api-reference/chainlogic/chains.md
  docs/docs/chainlogic/chains.md
  docs/docs/chainlogic/crosschain.md
  docs/docs/chainlogic/supported.md
  docs/docs/getting-started/actions.md
  docs/docs/getting-started/creatingminiapp.mdx
  docs/docs/getting-started/keyconcepts.md
  docs/docs/getting-started/metadata.md
  docs/docs/getting-started/quickstart.md
  docs/docs/guides/guide-en.md
  docs/docs/guides/guide-es.md
  docs/docs/intro.mdx
  docs/docs/keyconcepts/creatingminiapp.mdx
  docs/docs/keyconcepts/examples.md
  docs/docs/keyconcepts/keyconcepts.md
  docs/docs/keyconcepts/metadata.md
  docs/docs/keyconcepts/nextsteps.md
  docs/docs/keyconcepts/stepbystep.md
  docs/docs/sdk/parameters.md
  docs/sidebars.ts
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  src/examples/transfer-miniapps.ts
  src/interface/chains.ts
  src/templates/templates.ts
  src/validators/blockchainActionValidator.ts
  src/validators/transferActionValidator.ts
Labels: enhancement

#83 [Merge] Develop into Main: Deploy Docs
  README.md
  docs/docs/api-reference/action-types/blockchain-actions.md
  docs/docs/api-reference/action-types/http-actions.md
  docs/docs/api-reference/action-types/nested-action-flows.md
  docs/docs/api-reference/action-types/transfer-actions.md
  docs/docs/api-reference/chainlogic/chains.md
  docs/docs/chainlogic/chains.md
  docs/docs/chainlogic/crosschain.md
  docs/docs/chainlogic/supported.md
  docs/docs/getting-started/actions.md
  docs/docs/getting-started/creatingminiapp.mdx
  docs/docs/getting-started/keyconcepts.md
  docs/docs/getting-started/metadata.md
  docs/docs/getting-started/quickstart.md
  docs/docs/guides/guide-en.md
  docs/docs/guides/guide-es.md
  docs/docs/intro.mdx
  docs/docs/keyconcepts/creatingminiapp.mdx
  docs/docs/keyconcepts/examples.md
  docs/docs/keyconcepts/keyconcepts.md
  docs/docs/keyconcepts/metadata.md
  docs/docs/keyconcepts/nextsteps.md
  docs/docs/keyconcepts/stepbystep.md
  docs/docs/sdk/parameters.md
  docs/sidebars.ts
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  src/examples/transfer-miniapps.ts
  src/interface/chains.ts
  src/templates/templates.ts
  src/validators/blockchainActionValidator.ts
  src/validators/transferActionValidator.ts
Labels: enhancement

#84 Feature/support post serialize tx
  docs/docs/api-reference/parameters/parameters.md
  docs/docs/sdk/validation.md
  docs/docs/tutorial-basics/_category_.json
  docs/docs/tutorial-basics/congratulations.md
  docs/docs/tutorial-basics/create-a-blog-post.md
  docs/docs/tutorial-basics/create-a-document.md
  docs/docs/tutorial-basics/create-a-page.md
  docs/docs/tutorial-basics/deploy-your-site.md
  docs/docs/tutorial-basics/markdown-features.mdx
  docs/docs/tutorial-extras/_category_.json
  docs/docs/tutorial-extras/img/docsVersionDropdown.png
  docs/docs/tutorial-extras/img/localeDropdown.png
  docs/docs/tutorial-extras/manage-docs-versions.md
  docs/docs/tutorial-extras/translate-your-site.md
  docs/sidebars.ts
Labels: documentation, enhancement
